"vimrc file Bethany Armitage

map <leader>n yyp<C-a>

"change tabs to spaces
"    :retab

execute pathogen#infect()
filetype plugin indent on

 syntax enable
 colo elflord
" colo blue
" colo murphy
" colo pablo

set number          "show line numbers

"highlight Normal ctermfg=grey ctermbg=black

set backspace=indent,eol,start

set showmode

set shiftwidth=2    "set indents to have a width of 4

set tabstop=2       "4 spaces for each tab

set expandtab       "expands tabs to spaces

set smartindent

set hlsearch

set incsearch

set numberwidth=5

set nowrap

set laststatus=2

" highlight LineNr ctermfg=grey

" this is supposed to help with system clipboard pasting,
" doesn't seem to work for mac.
set clipboard=unnamed

" I never use shift-k,
" it just makes me stop what I'm doing when I hit it by accident
nnoremap <S-K> <Nop>

noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>
inoremap <Up> <nop>
inoremap <Down> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>

" right arrow puts in paste mode and opens a new line,
" left arrow udoes passte mode
nnoremap <silent> <right> :set paste <CR> o
nnoremap <silent> <left> :set nopaste <CR> <C-O>

" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>

" <Ctrl-w> hightlights whitespace
nnoremap <silent> <C-w> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>

set rtp+=/Users/beth/Library/Python/2.7/lib/python/site-packages/powerline/bindings/vim

" <Ctrl-n> toggles nerdtree
"map <silent> <C-n> :NERDTreeToggle<CR>


